baseURL = "https://erikfwinter.github.io/"
languageCode = "en-en"
title = "Hi, I'm Erik-F Winter!"
theme = "aerial"

[params]
  name = "Erik-F Winter"
  about = "Someone looking into hugo and static content web sites"
  description = "Someone looking into hugo and static content web sites"
  language = "en"
  copyright = "2019 Erik-F Winter"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"
  googleanalytics = "UA-132759579-1"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/ErikFWinter"
  target = "_top"

[[params.social]]
  medium = "Stackoverflow"
  icon = "stack-overflow"
  link = "https://stackoverflow.com/users/1414318/erikfwinter"
  target = "_top"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/ErikFWinter"
  target = "_top"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "javascript:document.location='mail'+'to:'+atob('ZXJpay5mLndpbnRlckBnbWFpbC5jb20=');"
  target = ""

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/erikfwinter/"
  target = "_top"

[[params.social]]
  medium = "xing"
  icon = "xing"
  link = "https://www.xing.com/profile/ErikFelix_Winter/"
  target = "_top"